// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIJ2VXhiQRjwYLnyaQ8w2PyYiAc0lf1jo',
    appId: '1:60137798945:web:e9da212e0b00c7b4e99260',
    messagingSenderId: '60137798945',
    projectId: 'projetoflutter1-e3626',
    authDomain: 'projetoflutter1-e3626.firebaseapp.com',
    storageBucket: 'projetoflutter1-e3626.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFGwuAz2-txXICzWv9aBSIP7A5MpNN_dc',
    appId: '1:60137798945:android:c0e441d608a13f24e99260',
    messagingSenderId: '60137798945',
    projectId: 'projetoflutter1-e3626',
    storageBucket: 'projetoflutter1-e3626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtvAP4DwvG4t2iSxHkn310rUKSwkF0ER0',
    appId: '1:60137798945:ios:581a6987d18559d4e99260',
    messagingSenderId: '60137798945',
    projectId: 'projetoflutter1-e3626',
    storageBucket: 'projetoflutter1-e3626.appspot.com',
    iosBundleId: 'com.example.autoControlPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtvAP4DwvG4t2iSxHkn310rUKSwkF0ER0',
    appId: '1:60137798945:ios:581a6987d18559d4e99260',
    messagingSenderId: '60137798945',
    projectId: 'projetoflutter1-e3626',
    storageBucket: 'projetoflutter1-e3626.appspot.com',
    iosBundleId: 'com.example.autoControlPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIJ2VXhiQRjwYLnyaQ8w2PyYiAc0lf1jo',
    appId: '1:60137798945:web:f7bf8017c6ad5529e99260',
    messagingSenderId: '60137798945',
    projectId: 'projetoflutter1-e3626',
    authDomain: 'projetoflutter1-e3626.firebaseapp.com',
    storageBucket: 'projetoflutter1-e3626.appspot.com',
  );
}
